Mwo 11 statuses
MWO-team2/Dziekanat pull request #21
Opened 2018-03-24 17:19 UTC by kkalista

Solve #11

2018-03-24 17:21 UTC, kkalista commented
Hej Panowie,
Zrobiłam to jak potrafiłam, proszę o komentarze.

2018-03-25 13:25 UTC, Yankowski requested changes

2018-03-25 13:25 UTC, Yankowski commented on src/main/java/com/mwo/group2/Administrator.java
> +	/*public void printReport(Report report) { ---> nie wiem jak to zaimplementowac
tutaj trzeba przedyskutować, co by ten printRaport miał drukować(czego ten raport ma dotyczyć?, może na początku wystarczy  coś w tylu "System.out.println(raport)" a potem to rozszerzymy?, na rysnku klasy nie przyjmuje on żadnych argumentów,

2018-03-25 13:25 UTC, Yankowski commented on src/main/java/com/mwo/group2/Administrator.java
> +	/*public boolean changeCourse() { ---> po co mamy to implementowac?
ja też nie widzę celu w pisaniu takiej metody, wyrzuć proszę ten kod, tak, abyśmy nie trzymali zakomentowanych metod w naszym projekcie:)

2018-03-26 08:05 UTC, astutus requested changes
@kkalista :  masz tam kilka drobnostek do poprawy, 
Po za tym po edycji pliki: click Source w eclipse i format (albo ctrl+shift+f)
Jak zrobisz zmiany, to push DO SIEBIE, do swojego fork'a to sie automatyczne tutaj zscyncuje.

2018-03-26 17:26 UTC, kkalista commented
Cześć wszystkim,
- usunęłam zbędne komentarze
- dopisałam drukowanie raportów
- postawiłam enter na końcu i sformatowałam kod

Dodatkowo, pozbyłam się Grade enum w tym pull request. Został tylko w #20 

Pozdrawiam,
Kasia

2018-03-27 04:30 UTC, Yankowski approved these changes
super:)

2018-03-27 14:38 UTC, astutus approved these changes
doskonale, wszstko jest ok

2018-03-27 14:39 UTC, merged